### ISSUE TITLE
category level status

### ISSUE THREAD

**Issue by logicminds** [cstate/cstate#101]
**Describe the solution you'd like**
Add status to right of category.  The category can often represent many systems so it would be awesome to see which category is operational, degraded or down. 

This is in addition to the system status. 
Some like the following: https://status.python.org/

**Comment by mistermantas** [comment]
Slightly tricky to do but not a bad idea. Thank you for the suggestion.

**Comment by ANONYM-ANONYM** [comment]
Good idea. Also can you please add option that users can subscribe to updates using Discord and Slack webhooks?
Also i would like feature to show status icons next to the status text.
For example fontawesome icons.
Or add config option to create custom statuses with custom text, color and icon
![image](https://user-images.githubusercontent.com/70404616/94139325-c0546900-fe69-11ea-95c0-8d1e61bbb5b2.png)

**Comment by mistermantas** [comment]
I will reply to ANONYM shortly with:

I'm sorry, I can't do any of these things which are, by the way, _unrelated to this issue_. They're opinionated or simply... impossible for me to do.

> Also i would like feature to show status icons next to the status text.

You can add that with custom CSS or by overriding the language files and using emoji.

> For example fontawesome icons.

FA is far too large of an asset for it to be added as a dependency.
 
You can look for another project if you want more random features.

**Comment by ANONYM-ANONYM** [comment]
@mistermantas OK, Thanks for explanation. Can you please tell me where can i add custom css or modify status text (i want to change "Maintenance" status to "Announcement" for my statuspage)

**Comment by mistermantas** [comment]
> @mistermantas OK, Thanks for explanation. Can you please tell me where can i add custom css or modify status text (i want to change "Maintenance" status to "Announcement" for my statuspage)

https://github.com/cstate/cstate/wiki/Customization#custom-html - custom CSS

https://github.com/cstate/cstate/wiki/Translations#add-your-translations - changing text

**Comment by ANONYM-ANONYM** [comment]
Thanks, but i want to change text (modify english version) just for my StatusPage where should i add translation file? I have this in themes folder: 
![image](https://user-images.githubusercontent.com/70404616/94260237-168bdf80-ff30-11ea-8150-0e347867ca75.png)
and this folders: 
![image](https://user-images.githubusercontent.com/70404616/94260281-2a374600-ff30-11ea-8a46-f01478761654.png)

**Comment by ANONYM-ANONYM** [comment]
@mistermantas Sorry for ping, please help me to change text just for my StatusPage, i dont want to create theme

**Comment by mistermantas** [comment]
> @mistermantas Sorry for ping, please help me to change text just for my StatusPage, i dont want to create theme

It's fine to ask but next time **please create a new issue instead of invading a completely irrelevant one**. I cannot guarantee response times for free projects.

You are not supposed to create a theme, where did you get that from? Genuinely, maybe I wrote the documentation wrong or something?

1. **In your site repository root** (where you see the folders `content, layouts, netlify, static` create a new folder called `i18n`.
2. Create a new file inside called `en.yaml` or whatever other language your base site is in. I'm assuming it's in English.
3. Now you can override whatever translations you wanted to change, that is, write new ones - https://github.com/cstate/cstate/blob/master/i18n/en.yaml - follow this format.

This shouldn't break cState but for future updates, but you always risk weird behavior when modifying something -- follow the changelogs before updating in the future.

(Also, if everything works and you understood what I said -- just give a thumbs up and do not reply because I think other people subscribed to issue might get interrupted. Thank you! For further questions, as I said earlier, create a new issue.)

Have a wonderful weekend.

**Comment by ANONYM-ANONYM** [comment]
@mistermantas Hi, sorry that i am writing again to this issue. But I need help. I added css for iconify icons to head and i added iconify css icons to statuses in en.yaml file. But icons are not working :/ 
![20200927_165134](https://user-images.githubusercontent.com/70404616/94367932-c6ed1580-00e1-11eb-93cc-77a8549b2b2d.png)

**Comment by soinu** [comment]
> The category can often represent many systems so it would be awesome to see which category is operational, degraded or down.

Additionally to just showing the overall status systems behind a category it would be nice to announce maintenance / report an issue which affects every system in a category.

**Comment by mistermantas** [comment]
I'll try to add this in the next round of development with JS and hopefully close this issue :)

> Additionally to just showing the overall status systems behind a category it would be nice to announce maintenance / report an issue which affects every system in a category.

this is now available on the v5 API but impractical for a UI

if this main feature were to implemented, probably some notice like this should be here too

![image](https://user-images.githubusercontent.com/11616378/109021561-a9899b00-76c3-11eb-8bba-7fec08d96b8e.png)

**Comment by mistermantas** [comment]
This has been implemented in v5 using JavaScript (client side scripting) since it's not mission critical information. Pushing this out soon.

Here's an example (North Coast category is empty; East Coast has two systems which are Operational and Maintenance respectively):

![image](https://user-images.githubusercontent.com/11616378/110208844-1ce49700-7e92-11eb-84a4-60bfcd2d5729.png)


As is always, you can view information without JS on:

![image](https://user-images.githubusercontent.com/11616378/110208779-c8411c00-7e91-11eb-952c-40ec3924f421.png)

**Comment by mistermantas** [comment]
The implementation is similar to other sites. Category status disappears when it's open.

![image](https://user-images.githubusercontent.com/11616378/110209139-6f728300-7e93-11eb-99ef-a53f220a7949.png)
