### ISSUE TITLE
Seperate CSS file

### ISSUE THREAD

**Issue by avronr** [cstate/cstate#118]
Hey,

I can't find proper CSS in the repo files. It would be great if you guys could use a CSS file that we could use to style our status pages. Right now I can't find any CSS in the repo and I do not know where to look. if there's a way to do this right now please let me know.

Cheers

**Comment by mistermantas** [comment]
cState uses <style> tags. It's an intentional decision so 1 HTTP request can fetch the most important things.

https://github.com/cstate/cstate/wiki/Customization#where-custom-html-can-be-added

> You can add meta tags, custom styling, and any other type of HTML that should be loaded as soon as possible and hidden from the user.

Edit `partials/custom/meta.html` **but not in the themes/cstate folder.** This separation is important to ensure the most core CSS is always available and can be updated by the developers — so, me.

**Comment by avronr** [comment]
@mistermantas the logo in the header is aligned to the left. It does look a bit odd. I can make a PR with CSS that will center the logo to the center but which file should I add the style to? again I'm talking about the header logo. To the partial file?

**Comment by mistermantas** [comment]
> @mistermantas the logo in the header is aligned to the left. It does look a bit odd. I can make a PR with CSS that will center the logo to the center but which file should I add the style to? again I'm talking about the header logo. To the partial file (header.html)? 

Okay I don't think you have fully read — or rather, seen — all the existing capabilities of cState that don't require making any custom CSS.

This is the wiki

https://github.com/cstate/cstate/wiki

Under "Design / Changing header", you can use the "large design" which centers the logo

https://github.com/cstate/cstate/wiki/Customization#changing-header

A small logo by default is shown to the left. This is an intentional design decision.

**If you go to edit the header.html, you will see that there is no CSS there.**

I have, yet again, purposefully designed the thing to have a separation of concerns.

**Any custom CSS** you want to make # would go into your `layouts/partials/custom/meta.html` file. **It should be a blank file, and you should not edit anything in the themes/cstate directory**, though I think I've made that clear earlier.

If you need to add custom HTML, you could use the other html files in `layouts/partials/custom`.

All the custom partials should be empty, they're just injected into the website in different places which is why there are so many custom partials. They could have CSS in them, because any HTML can be there, but that's just really not smart from my POV if you want global CSS changes.

But again, you can make a lot of edits just with the `config.yml` file which is why the wiki is so important.

I hope I've explained these things in a way that makes sense. :)

**Comment by avronr** [comment]
Yes. Thanks.
