### ISSUE TITLE
Status embed (and other feature requests)

### ISSUE THREAD

**Issue by ririko5834** [cstate/cstate#131]
**Is your feature request related to a problem? Please describe.**
These are my feature requests.

**Describe the solution you'd like**

**My feature requests are:**

- Add option to create multiple incident templates using config.yml file and option to choose incident template when creating new incident from Netlify CMS dashboard. I think that this could be useful for others, not just me.

- Create Status Embed widget that you can add to your websites and it will be displayed if there is some incident. Something like statuspage.io widget.
![image](https://user-images.githubusercontent.com/64729293/94909306-45133880-04a3-11eb-91a2-6eb0ab5f6f0c.png)

- Create option for displaying uptime in % for systems using UptimeRobot API

**Comment by mistermantas** [comment]
1. Netlify CMS does not have templates to my knowledge. Sorry.
2. This would be an external project. A fun suggestion though! I like it.
3. Again, I'm not sure what I can do here because you're using an external API even.

**Comment by ririko5834** [comment]
:(Its sad that netlify CMS does not support templates. Can you add that i can choose which systems are affected? 
![image](https://user-images.githubusercontent.com/64729293/94985957-fde87e80-055a-11eb-88fd-617282bb8d15.png) 
Something like this menu for choosing systems:
![image](https://user-images.githubusercontent.com/64729293/94985971-22dcf180-055b-11eb-8395-c0074341e52c.png)

**Comment by ririko5834** [comment]
And can i modify default incident text?
![image](https://user-images.githubusercontent.com/64729293/94985998-4f910900-055b-11eb-8eeb-e0b40e89fd23.png)


Also

> This would be an external project. A fun suggestion though! I like it.

Can you please make it? 

And where are Pages that were published from netlify CMS dashboard served? (idk how to find them on website)

**Comment by mistermantas** [comment]
You can add that manually, if you so wish, by overriding the Netlify CMS
config.yml

The drop-down list can't be populated automatically, unfortunately.

**Comment by mistermantas** [comment]
A few thoughts on point #2 - Status Embed (I changed the title for clarity)

An embed works like this:

1. It asks the server (the status page, in this case) what the status is
   * There's a read-only API for this purpose, so you check the `summaryStatus`
2. If the status is `disrupted` or whatever, you initiate some UI (like the alert you sent)

Not a lot of logic behind this (unless you want to add a lot of checks and stuff!)

Some nuances:

- In my example, this checking **only happens on the page load and does not repeat**
- Repeating this many times (every x minutes, if you have a single page app or whatnot) is unproductive because, well, I hope your site doesn't go down THAT often + the bandwidth used should be taken into consideration
- Therefore, if you load your page, then your status page's summary state changes, the user won't know until the page is reloaded

I tried this code, it's just a basic initiation of step 1:

```js
fetch('https://cstate.mnts.lt/index.json')
  .then(response => response.json())
  .then(data => console.log(data));
```

and I remembered why I don't like JavaScript and fetch() - CORS. This is not my full-time project, but I'll try to Google my way through this because it's likely that:

- you may need to set up the headers (or something) to let `fetch()` checks happen securely or whatever
- i am a bad developer or whatever

Discuss here!

Send PRs here: https://github.com/cstate/html-embed

**Comment by mistermantas** [comment]
I found a fix for the CORS issue!

If you open console and enter:

```js

fetch('https://flamboyant-shirley-6bc75e.netlify.app/index.json')
  .then(response => response.json())
  .then(data => console.log(data));
```

...you will see that this code works and doesn't throw any errors as opposed to the old code.

The Netlify site in question is my testing repo. What I did was add this bit of code to the end of `netlify.toml`:

```toml
[[headers]]
    for = "/*.json"
    [headers.values]
      Access-Control-Allow-Origin = "*"
```

This should be 100% safe because, as you can, only JSON pages have the wildcard attached to `Access-Control-Allow-Origin`.

Also, _technically_ cState is supposed to be used fully for public purposes only and only its static files served (so you don't have logins on the same domain, like status.example.com/superimportantlogin or whatever).

This bit of code will be added to the next release whenever the HTML embed becomes available. :)

**Comment by mistermantas** [comment]
**Important note for people already using cState or those who have not upgraded to the (as of writing, non-existent) version**

You can just add this code to netlify.toml now and make the read-only API (that is, those pages) work as intended

The thing is you'd have to do that anyway after updating. Only the exampleSite can be updated to make this work — it's not something under /themes/ that I can change as I see fit.
