### ISSUE TITLE
"Resolved in under a minute"

### ISSUE THREAD

**Issue by xHyroM** [cstate/cstate#145]
Hello!
I would like to ask why the page "Resolved in under a minute" always shows me when it was resolved in about 2/3 hours

Screen:
https://imgur.com/WTd6PlE

Status Page:
https://status.hyro.tech

**Comment by mistermantas** [comment]
In your frontmatter, you need to define the start of the issue for `Date` (that is, when the issue started).

When you fix the issue, you need to add a date, in the same format, to the `ResolvedWhen`.

I looked at your file and **your `Date` and `ResolvedWhen` are the same which is why you are not seeing any other calculations**:

https://status.hyrousek.tk/issues/2020-09-30-website-down/index.json
