### ISSUE TITLE
Customization does not work

### ISSUE THREAD

**Issue by Sarveshmrao** [cstate/cstate#146]
**Describe the bug**
Customization for custom HTML does not work

**Reproduction steps**
Steps to reproduce the behaviour:
1. Create partials/custom/meta.html
2. Put custom styles In it within `<style>...</style>`
3. Commit
4. No change in website

**Expected behaviour**
As per my expectation, the page should change as per the styles

**Comment by xHyroM** [comment]
no /custom only layouts/partials/meta.html

**Comment by mistermantas** [comment]
> no /custom only layouts/partials/meta.html

Please do not overwrite the main files. If you do this, it'll be harder to update for you to another version and there's v4.4 just around the corner...

***

@Sarveshmrao, this file should be housed inside your website directory: `/layouts/partials/custom/meta.html`

**Your website root should not have a `partials` folder.** Is there documentation that led you to believe otherwise? I'll fix it so other people don't have this issue in the future. :)

Also make sure `Site.Params.enableCustomHTML` is true. Add (if it's not there already) `enableCustomHTML: true` under the `Params:` tree.

**Comment by Sarveshmrao** [comment]
Thanks, @mistermantas that worked. Yes, the wiki was the place which guided me in such a way. Now how do I remove the `--small` from the Logo image?

**Comment by mistermantas** [comment]
> Thanks, @mistermantas that worked. Yes, the wiki was the place which guided me in such a way. Now how do I remove the `--small` from the Logo image?

That's also a config option. Look for "logo" in the Wiki sidebar under "Customization"

**Comment by Sarveshmrao** [comment]
Is this the one?? https://github.com/cstate/cstate/wiki/Customization#title--logo
I can't find any customization option here.

**Comment by mistermantas** [comment]
> Is this the one?? [cstate/cstate/wiki/Customization#title--logo](https://github.com/cstate/cstate/wiki/Customization#title--logo)
> I can't find any customization option here.

Scroll up just a bit

https://github.com/cstate/cstate/wiki/Customization#design

**Comment by Sarveshmrao** [comment]
How can I change remove the `--small` with that? It's just for changing logo and enabling it.
