### ISSUE TITLE
Move source location in Netlify resulted in all incidents being lost in admin page

### ISSUE THREAD

**Issue by pauby** [cstate/cstate#177]
**Describe the bug**
We recently moved the GitLab repository location for our cstate code and since then, we are not able to see any previous incidents in the Admin portal. We can still see them on the site, however.

We did update the `Repository` settings under `Build Settings` but that didn't fix the issue.

**Reproduction steps**
1. Log into the admin portal / page.

**Expected behavior**
That we can see all of the historical incidents in the admin portal / page.

**Screenshots**

![image](https://user-images.githubusercontent.com/12760779/114909992-df6a1680-9e0c-11eb-8f31-3331c1f62200.png)

You can see from the above there are no incidents shown. However, if you go to https://status.chocolatey.org you can see there are a lot of historical incidents.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 87.0

**Additional context**
We are using 3.1.1 of cstate.

**Comment by mistermantas** [comment]
Thanks for using the status page.

The CMS is made by Netlify, so ssues regarding it should be looked into with them:

https://www.netlifycms.org/docs/gitlab-backend/ You could use the direct GitLab login

https://www.netlifycms.org/docs/git-gateway-backend/ Or if you are using Git Gateway with Netlify, here are the docs for that. I suspect if you are using this method, the issue is this: Git Gateway is not synced to the new repo on netlify.com

![150954B3-4DFF-4B11-A27B-0691FCDBA950](https://user-images.githubusercontent.com/11616378/114911543-cae74780-9e27-11eb-8ce2-abb0f138b65e.jpeg)

**Comment by mistermantas** [comment]
Let me know if this helped.
