### ISSUE TITLE
Add support for Discord and Slack webhook notifications

### ISSUE THREAD

**Issue by ririko5834** [cstate/cstate#187]
There should be added that you can set webhook urls where notifications on new incidents and resolved incidents will be posted

**Comment by mistermantas** [comment]
This is not possible.

**Comment by ririko5834** [comment]
Why?

**Comment by mistermantas** [comment]
Because cState is a theme for a **static** site generator.

The best I can offer you is to use the webhooks Netlify or your other hosting provider offers to alert users or staff about a new deploy.

It is not possible to send webhooks based on what kind of issue change there is with the core of cState.

Please look at the cState HTML Embed and wiki for ideas.
