### ISSUE TITLE
Show date for future issues.

### ISSUE THREAD

**Issue by asciiphil** [cstate/cstate#199]
It would be nice if there were a little more distinction between future and ongoing issues.  In particular, I'd like to see the date for future issues (a.k.a. scheduled maintenance).  Maybe something like "Scheduled for <formatted date>" either right before or right after the title in the announcement box?

**Comment by mistermantas** [comment]
good idea :) ongoing is just the string used for unresolved issues though

**Comment by mistermantas** [comment]
I haven't looked at cState in a long time, as evident by the comment from nearly a month ago, but it turns out I had already thought about this since the date IS shown in the corner but just in a small print so I'm not quite sure what to change? just maybe make the date more easy to read / see?

<img width="788" alt="08-23 at 16 56 44@2x" src="https://user-images.githubusercontent.com/11616378/130460027-b177b783-b7d9-4b99-9fc1-ae5266344a48.png">

**Comment by mistermantas** [comment]
<img width="876" alt="08-23 at 17 05 52@2x" src="https://user-images.githubusercontent.com/11616378/130461344-7040f904-3c9b-483e-898b-bb575ff0b894.png">


I just moved it.

**Comment by mistermantas** [comment]
this isn't in a new release by the way but if you download from the master branch you can take advantage of this feature or look at the commit to override the file locally for yourself
