### ISSUE TITLE
External link button to link to a component

### ISSUE THREAD

**Issue by aperullo** [cstate/cstate#214]
**Is your feature request related to a problem? Please describe.**
Some services/components have web frontends, It would be a nice-to-have to be able to link to them. 

**Describe the solution you'd like**
Add an optional link field to the config file under each component that will then show a button that will take one to the url.

**Describe alternatives you've considered**
None in particular.

**Additional context**
I have put together a [branch with the change](https://github.com/cstate/cstate/compare/master...aperullo:master), but wasn't sure if it conforms to this projects' specific style. I haven't done frontend work (html/css) before so if there is a better way to do something please let me know. Otherwise I'll post a PR with the change.

External link image is from font awesome ([license](https://fontawesome.com/v4.7/license))

![image](https://user-images.githubusercontent.com/18688190/143311420-f99a433c-1e69-4f6c-a263-97f8fd33a05e.png)

I'm not sure how the proper way to deal with dark-mode, and the icon is hard to see with it enabled.

**Comment by mistermantas** [comment]
cstate, because it has to support IE8, doesn't really use SVGs - most of the icon elements are actually from unicode

https://www.quora.com/Is-the-symbol-for-external-link-available-in-Unicode-If-so-how-do-I-get-in-on-my-Mac the closest thing is this nice-looking arrow

I think this is a kind of cool idea, actually, though - i think i might add it in a future update whenever i've got something else to couple with this

**Comment by aperullo** [comment]
Thanks! I see, using text immediately solves the dark mode issue. I also looked through part of unicode and found some other character you might consider using as icons. I'm on linux so I can't check they all render on IE8 but here they are:

```
🡭 U+1F86D
🡵 U+1F875
🢅 U+1F885
🔗 U+1F517
```

![image](https://user-images.githubusercontent.com/18688190/143895557-fdaea1e1-16fd-4601-b2d9-d3abbea2c0c0.png)

For my eye, I like U+1F875. Though U+1F517 is the link emoji which might make it more immediately familiar, even if it looks kind of funky.

I'll update my branch as well.

![image](https://user-images.githubusercontent.com/18688190/143896760-e31d4d89-b1d3-47c7-9626-40eda6a35ef2.png)

**Comment by mistermantas** [comment]
Hi, you can make this into a PR so long as you:

- push to dev
- if you change 1rem to px (because, again, IE8 and we're just using px everywhere)
- and use  `🔗 U+1F517` as a default since it's the only one that consistently shows, although a little bit ugly... 
- I think the other link options can be provided in the wiki / comments. Only the default I've suggested seems to show up on Mac

I would also like to put this link on the pages for the systems themselves (when you click on the title) but I can do that myself since it's kind of outside of your feature request

**Comment by aperullo** [comment]
Yeah certainly not the prettiest. I wonder if it does any good to add the other unicode characters as options if we're looking to maintain that compatibility though. I would maybe just make note of "other options that were considered" in the PR?

Also updating wikis is strange since I can't directly submit PRs against them, so I've made a [gist](https://gist.github.com/aperullo/bc173f15ce4ba33325f634408d179696) with my edit to the "Systems" section, describing the new `link` property. If there is a better way to go about it please let me know.

Please let me know I missed anything, thank you!

https://github.com/cstate/cstate/pull/223
