### ISSUE TITLE
RSS Feed - CORS blocked

### ISSUE THREAD

**Issue by JXGA** [cstate/cstate#221]
**Is your feature request related to a problem? Please describe.**

When attempting to feed the cState RSS feed into Grafana, I encountered it was blocked by CORS. 

**Describe the solution you'd like**

Standardised CORS 'fix' for the RSS feed

**Describe alternatives you've considered**

N/A

**Additional context**

I followed from another of the CORS issues encountered and added the below into `netlify.toml`: 

```
[[headers]]
    for = "/*.xml"
    [headers.values]
      Access-Control-Allow-Origin = "*"
```

This resolved the 'issue' but I'm not sure it's best practice or the best solution.

Addition of the above code (or improved version!) might be considered for future upgrades if needed for other users. 

Thanks for the excellent project!

**Comment by mistermantas** [comment]
hi,

headers aren't defined by cstate, they're defined in the configurations of each individual website on each individual hosting provider (netlify, cloudflare pages, whatever else you use)

the default example repository has a boilerplate `netlify.toml` which has the exact same code, but for the JSON API (instead of RSS/XML)

thank you for letting me know RSS is blocked by CORS by default - definitely something that needs to be highlighted
