### ISSUE TITLE
Add more information to filename on Netlify CMS

### ISSUE THREAD

**Issue by SamWhited** [cstate/cstate#33]
**Is your feature request related to a problem? Please describe.**

When using Netlify CMS to create new issues, the title of the markdown file created is the title of the post. However, if you have weekly maintenance posts and try to title multiple of them "Weekly Maintenance" or something similar, only the first gets saved.

**Describe the solution you'd like**

Add a date, this also has the benefit of making posts sort correctly in most systems. Eg. instead of creating `weekly-maintenance.md` we would create `2018-10-07-weekly-maintenance.md`.

**Describe alternatives you've considered**

I also thought about suggesting things like the components affected or other metadata from the title, but this doesn't make files sort well and may still have the same problem. A date is more likely to make the file unique and easy to find later.

**Comment by mistermantas** [comment]
This isn't necessarily a problem of cState, but more of your use case.

You could very well put the date in the title. Might not be aesthetic, but it's one solution. `Weekly Maintenance of October 7th, 2018`

When I made cState, I didn't plan with that kind of thing in mind, all titles would be different, at least in some way, but because Netlify CMS is incredibly bad at working with titles, it's worth considering.

If I were to do this, however, maybe sorting by folder would make more sense? E.g. `status.example.com/2018/10/07/weekly-maintenance`

**Comment by SamWhited** [comment]
Folder makes sense to me as well; the real problem is that it silently drops the newly published issue and there's no way to see if the title will conflict, I probably should have filed that as a bug instead of a feature request. Using the date fixes the problem by making sure they can't conflict, but also makes it easier to edit offline as well as online. Thank you for your consideration.

> edit: you can also edit Netlify CMS settings but this isn't documented nor recommended. it's just a config file you could override under static

Good to know; I'll look into that.

**Comment by mistermantas** [comment]
For now I've come to the decision to just use `status.example.com/issues/2018-10-07-weekly-maintenance` by default on the example site and Netlify CMS — will be on #38.

I'd love to do folders, but Netlify CMS doesn't seem to be able to create files under a dynamic folder structure like that (`year/month/slug`). Might revisit it later.
