### ISSUE TITLE
feed is not valid

### ISSUE THREAD

**Issue by luto** [cstate/cstate#46]
**Describe the bug**

Newer versions (currently in the staging branch) of cstate provide a feed, which is awesome! :) Sadly, there seem to be a few issues with this new feature:

1. [it does not validate](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fpastebin.com%2Fraw%2Fw00SBJDN)
2. `https://reddit.statuspage.io` is mentioned as an alternative URL. While this might be true for reddit, it does not seem like a sane default.

**Reproduction steps**

```
cd exampleSite
mkdir themes
ln -s ../.. themes/cstate
hugo
cat public/index.xml
```

**Expected behavior**

The feed should survive a basic XML validation. If the feed does not know its HTML version, default to not providing any alternative links, instead of reddit.

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: v3 Beta 1, e21e127115fc3ef3799bb9c82373cbd5a955151d

**Comment by mistermantas** [comment]
Apologies! I'm not an RSS / Atom user myself — I can definitely fix the Reddit link which is just a horrible oversight by me and as for the validation... we will see.

What doesn't validate is of most interest to me right now, as you see.

**Comment by mistermantas** [comment]
Upon further exploration, this kind of seems like what you get when you use `/` on `baseURL`. It's a hack — always been — because otherwise incident links always point to the wrong location lol. Seems like this would be _an even different_ issue, but an important one to tackle. So essentially `baseURL` needs to be... the base URL now. For those issues I suppose I'll need to use `relURL` [Ref](https://discourse.gohugo.io/t/solved-what-should-be-used-for-the-value-of-site-baseurl/5896/3)

There's other issues, too, but those seem to be with me not knowing how Atom works. I'll try to fix those.
